apiVersion: v1
kind: Service
metadata:
  name: tcpd-bench
spec:
  selector:
    name: tcpd
  clusterIP: None
---
apiVersion: v1
kind: Pod
metadata:
  name: tcpd-bench-server
  labels:
    name: tcpd
  annotations:
    networking.gke.io/default-interface: 'eth0'
    networking.gke.io/interfaces: |
      [
        {"interfaceName":"eth0","network":"default"},
        {"interfaceName":"eth1","network":"tcpx-eu-net-1"},
        {"interfaceName":"eth2","network":"tcpx-eu-net-2"},
        {"interfaceName":"eth3","network":"tcpx-eu-net-3"},
        {"interfaceName":"eth4","network":"tcpx-eu-net-4"}
      ]
spec:
  hostname: server
  subdomain: tcpd-bench
#  hostNetwork: true
#  dnsPolicy: ClusterFirstWithHostNet
  containers:
    # This container is here to debug DNS resolution
    #- name: debug
    #  image: tianon/network-toolbox
    #  command:
    #  - /bin/sh
    #  - -c
    #  - for i in $(seq 1 10); do echo "Iteration $i"; dig +short server.tcpd-bench.default.svc.cluster.local; sleep 1; done; sleep inf
    - name: tcpd-daemon
      image: us-docker.pkg.dev/gce-ai-infra/gpudirect-tcpx/tcpgpudmarxd:latest
      imagePullPolicy: Always
      command:
        - /tcpgpudmarxd/build/app/tcpgpudmarxd
        - --gpu_nic_preset
        - a3vm
        - --gpu_shmem_type
        - fd
      securityContext:
        privileged: true
      volumeMounts:
        - name: nvidia
          mountPath: /usr/local/nvidia/lib64
        - name: tcpd-socket
          mountPath: /tmp
      env:
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
        - name: IS_SERVER
          value: 'yes'
        - name: SERVER
          value: server.tcpd-bench.default.svc.cluster.local
        - name: CLIENT
          value: client.tcpd-bench.default.svc.cluster.local
    - name: server
      image: us-docker.pkg.dev/a3-tcpd-staging-hostpool/stable/sock-devmem-comm:latest
      imagePullPolicy: Always
      command:
        - /bin/sh
        - -c
        - sleep 10; /sock-devmem-comm/build/multinic_bench --gpus 0,1,2,3,4,5,6,7 --ifnames eth1,eth1,eth2,eth2,eth3,eth3,eth4,eth4 --use_dmabuf --port 5201 --num_gpus=8 --message_size 819200 --server_address "${SERVER}" --socket_per_thread 1 --threads_per_gpu 16 --skip_rx_copy --server
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
      volumeMounts:
        - name: tcpd-socket
          mountPath: /tmp
      env:
        - name: SERVER
          value: server.tcpd-bench.default.svc.cluster.local
      resources:
        limits:
          nvidia.com/gpu: 8
  volumes:
    - name: nvidia
      hostPath:
        path: /home/kubernetes/bin/nvidia/lib64
    - name: tcpd-socket
      emptyDir:
---
apiVersion: v1
kind: Pod
metadata:
  name: tcpd-bench-client
  labels:
    name: tcpd
  annotations:
    networking.gke.io/default-interface: 'eth0'
    networking.gke.io/interfaces: |
      [
        {"interfaceName":"eth0","network":"default"},
        {"interfaceName":"eth1","network":"tcpx-eu-net-1"},
        {"interfaceName":"eth2","network":"tcpx-eu-net-2"},
        {"interfaceName":"eth3","network":"tcpx-eu-net-3"},
        {"interfaceName":"eth4","network":"tcpx-eu-net-4"}
      ]
spec:
  hostname: client
  subdomain: tcpd-bench
#  hostNetwork: true
#  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: tcpd-daemon
      image: us-docker.pkg.dev/gce-ai-infra/gpudirect-tcpx/tcpgpudmarxd:latest
      imagePullPolicy: Always
      command:
        - /tcpgpudmarxd/build/app/tcpgpudmarxd
        - --gpu_nic_preset
        - a3vm
        - --gpu_shmem_type
        - fd
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - name: nvidia
          mountPath: /usr/local/nvidia/lib64
        - name: tcpd-socket
          mountPath: /tmp
      env:
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
        - name: SERVER
          value: server.tcpd-bench.default.svc.cluster.local
        - name: CLIENT
          value: client.tcpd-bench.default.svc.cluster.local
    - name: client
      image: us-docker.pkg.dev/a3-tcpd-staging-hostpool/stable/sock-devmem-comm:latest
      imagePullPolicy: Always
      command:
        - /bin/sh
        - -c
        - sleep 15; /sock-devmem-comm/build/multinic_bench -gpus 0,1,2,3,4,5,6,7 --ifnames eth1,eth1,eth2,eth2,eth3,eth3,eth4,eth4 --use_dmabuf --port 5201 --num_gpus=8 --message_size 819200 --server_address "${SERVER}" --socket_per_thread 1 --threads_per_gpu 16 --skip_rx_copy
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
      volumeMounts:
        - name: tcpd-socket
          mountPath: /tmp
      env:
        - name: SERVER
          value: server.tcpd-bench.default.svc.cluster.local
      resources:
        limits:
          nvidia.com/gpu: 8
  volumes:
    - name: nvidia
      hostPath:
        path: /home/kubernetes/bin/nvidia/lib64
    - name: tcpd-socket
      emptyDir: