apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: installer-fixup
  namespace: kube-system
  labels:
    k8s-app: installer-fixup
spec:
  selector:
    matchLabels:
      k8s-app: installer-fixup
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: installer-fixup
        k8s-app: installer-fixup
    spec:
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-accelerator
                    operator: In
                    values:
                      - nvidia-h100-80gb
      tolerations:
        - operator: "Exists"
      initContainers:
        - image: ubuntu
          name: installer
          securityContext:
            privileged: true
          volumeMounts:
          command:
            - nsenter
            - -at
            - '1'
            - --
            - sh
            - -c
            - "/usr/bin/ctr -n k8s.io images pull $(/usr/bin/cos-extensions list -- --gpu-installer) && /usr/bin/ctr -n k8s.io images tag $(/usr/bin/cos-extensions list -- --gpu-installer) docker.io/library/cos-nvidia-installer:fixed"
      containers:
        - image: "gcr.io/google-containers/pause:2.0"
          name: pause