apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tcpx-metrics
  namespace: kube-system
  labels:
    k8s-app: tcpx-metrics
spec:
  selector:
    matchLabels:
      k8s-app: tcpx-metrics
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: tcpx-metrics
        k8s-app: tcpx-metrics
    spec:
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-accelerator
                    operator: In
                    values:
                      - nvidia-h100-80gb
      tolerations:
        - operator: "Exists"
      hostNetwork: true
      containers:
        - image: gcr.io/gracegao-gke-dev/tcpx-metrics-server:latest
          name: tcpx-metrics
          resources:
            requests:
              cpu: 150m
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CONTAINER_NAME
              value: "tcpx_metrics"
#

